BBPATH .= ":${LAYERDIR}"

BBFILES += "${LAYERDIR}/recipes*/*/*.bb ${LAYERDIR}/recipes*/*/*.bbappend"

BBFILE_COLLECTIONS += "meta-unit-apps"
BBFILE_PATTERN_meta-unit-apps := "^${LAYERDIR}/"
BBFILE_PRIORITY_meta-unit-apps = "13"

LAYERDEPENDS_meta-unit-apps = "core"

LAYERSERIES_COMPAT_meta-unit-apps = "scarthgap styhead walnascar"

BBFILES_DYNAMIC += " \
    rust-bin-layer:${LAYERDIR}/dynamic-layers/rust-bin-layer/*/*/*.bb \
    rust-bin-layer:${LAYERDIR}/dynamic-layers/rust-bin-layer/*/*/*.bbappend \
"
